'use strict';

const expect = require('expect');
const extractFlights = require('../extractFlights');

describe('extractFlights', () => {
  it('should extract flight data from the html string', () => {
    const data = `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head><title>Keflavik Airport Arrivals. Scheduled & ETA - Keflavik International Airport- Kefairport.com</title><meta http-equiv="Content-Type" content="text/html; charset="/><meta name="description" content="Keflavik airport arrivals: Keflavik arrivals, scheduled and estimated times."/><meta name="keywords" content="keflavik airport arrivals, eta, keflavik international airport"/><meta name="robots" content="all"/><link rel="stylesheet" type="text/css" href="/resources/Styles/default-2010.css"/><script type="text/javascript" src="/framework/externals/forms.js"></script><script language="javascript" type="text/javascript" src="/resources/js/smoothfade.js"></script><link rel="shortcut icon" href="/favicon.ico" type="image/icon"><link rel="icon" href="/favicon.ico" type="image/icon"></head><body><div id="container"><div id="container-bottom"><div id="container-left"><div id="container-right"><div id="container-main"><div id="above"><div id="weather"></div><div id="shortcuts"><ul><li><a href="http://m.kefairport.com/" target="_self" onmouseover="window.status='Mobile'; return true" onmouseout="window.status=''; return true">Mobile</a></li><li><a href="/English/Shortcuts/About-us/" target="_self" onmouseover="window.status='About us'; return true" onmouseout="window.status=''; return true">About us</a></li><li><a href="http://b2b.kefairport.is/english" target="_self" onmouseover="window.status='B2B'; return true" onmouseout="window.status=''; return true">B2B</a></li><li><a href="/English/Sitemap/" target="_self" onmouseover="window.status='Sitemap'; return true" onmouseout="window.status=''; return true">Sitemap</a></li><li><a href="/English/Shortcuts/Statistics/" target="_self" onmouseover="window.status='Statistics'; return true" onmouseout="window.status=''; return true">Statistics</a></li><li><a href="/English/News/" target="_self" onmouseover="window.status='News'; return true" onmouseout="window.status=''; return true">News</a></li><li>|</li><li><a href="/"><img src="/resources/images/template/2010/bg-flag-is.gif" width="16" height="11"/></a></li><li><a href="/Deutsch/"><img src="/resources/images/template/2010/bg-flag-de.gif" width="16" height="11"/></a></li><li><a href="/Francais/"><img src="/resources/images/template/2010/bg-flag-fr.gif" width="16" height="11"/></a></li></ul></div><div id="search"><form method="post" action="/English/Search/" name="leit"> <div class="text"><input id="keywords" onblur="if(this.value==''){this.value='Search';}" onfocus="if(this.value=='Search'){this.value='';}" name="keywords" value="Search" type="text"/></div><input class="submit" type="submit" value="Search"/></form></div></div><div id="header"><div id="logo-container" class="en"><a class="logo" href="/English/">Keflavik International Airport</a> <a class="asq" href="/English/News/3001/Keflavik-International-Airport-best-in-Europe-in-2014/default.aspx">2014 ASQ</a></div><ul><li><span>Reykjavík</span><span class="clock" id="clock-0"><span class="no1">1</span><span class="no7">7</span><span>:</span><span class="no4">4</span><span class="no3">3</span></span></li><li><span>London</span><span class="clock" id="clock-1"><span class="no1">1</span><span class="no7">7</span><span>:</span><span class="no4">4</span><span class="no3">3</span></span></li><li><span>New York</span><span class="clock" id="clock-2"><span class="no1">1</span><span class="no2">2</span><span>:</span><span class="no4">4</span><span class="no3">3</span></span></li><li><span>Tokyo</span><span class="clock" id="clock-3"><span class="no0">0</span><span class="no2">2</span><span>:</span><span class="no4">4</span><span class="no3">3</span></span></li></ul><script type="text/javascript"><!--var iHours=17;var iMinutes=43;var iSeconds=43;var iOffset=new Array(0, 0, -5, 9);function formatValue(_iValue){if(_iValue < 10){_iValue="0" + _iValue;}return "" + _iValue;}function getNumberCode(_iNumber){return "<span class="no" + formatValue(_iNumber).charAt(0) + "">" + formatValue(_iNumber).charAt(0) + "</span><span class="no" + formatValue(_iNumber).charAt(1) + "">" + formatValue(_iNumber).charAt(1) + "</span>";}function setCounter(){if(++iSeconds > 59){iSeconds=0;if(++iMinutes > 59){iMinutes=0;if(++iHours > 23){iHours=0;}}var iTempHours=0;for(var i=0; i < 4; i++){iTempHours=iHours + iOffset[i];if(iTempHours > 23){iTempHours -=24;}else if(iTempHours < 0){iTempHours +=24;}document.getElementById("clock-" + i).innerHTML=getNumberCode(iTempHours) + "<span>:</span>" + getNumberCode(iMinutes);}}}setInterval("setCounter();",1000);--></script><div style="clear:right;float:right;width:320px;height:29px;position:relative;top:0px;#top:6px;left:10px;"><iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2FKeflavikurflugvollur%2F292868132138&amp;layout=standard&amp;show_faces=false&amp;width=320&amp;action=like&amp;font=arial&amp;colorscheme=light&amp;height=24" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:320px; height:29px;" allowTransparency="true"></iframe></div><div id="game"></div></div><div id="topmenu"><ul><li><a href="/english/" target="_self" onmouseover="window.status='Home'; return true" onmouseout="window.status=''; return true"><span>Home</span></a></li><li class="selected"><a href="/English/Timetables/" target="_self" onmouseover="window.status='Timetables'; return true" onmouseout="window.status=''; return true"><span>Timetables</span></a></li><li><a href="/English/Before-Departure/" target="_self" onmouseover="window.status='Before Departure'; return true" onmouseout="window.status=''; return true"><span>Before Departure</span></a></li><li><a href="/English/Transportation/" target="_self" onmouseover="window.status='Transportation'; return true" onmouseout="window.status=''; return true"><span>Transportation</span></a></li><li><a href="/English/For-the-passenger/Lost-Found/" target="_self" onmouseover="window.status='For the passenger'; return true" onmouseout="window.status=''; return true"><span>For the passenger</span></a></li><li><a href="http://www.kefairport.is/wheninkef/en/" target="_blank" onmouseover="window.status='Shops/Restaurants'; return true" onmouseout="window.status=''; return true"><span>Shops/Restaurants</span></a></li><li><a href="/English/Service/" target="_self" onmouseover="window.status='Service'; return true" onmouseout="window.status=''; return true"><span>Service</span></a></li><li><a href="/English/Visit-Iceland//Visit-Iceland/" target="_self" onmouseover="window.status='Visit Iceland'; return true" onmouseout="window.status=''; return true"><span>Visit Iceland</span></a></li></ul></div><div id="status-small"><ul class="nav-sub"><li><a class="active" href="/English/Timetables/Arrivals/" target="_self" onmouseover="window.status='Arrivals'; return true" onmouseout="window.status=''; return true"><span>Arrivals</span></a></li><li><a href="/English/Timetables/Departures/" target="_self" onmouseover="window.status='Departures'; return true" onmouseout="window.status=''; return true"><span>Departures</span></a></li><li><a href="/English/Timetables/Schedule/" target="_self" onmouseover="window.status='Schedule'; return true" onmouseout="window.status=''; return true"><span>Schedule</span></a></li></ul></div><div id="main"><div id="left"><div class="shops"><!--<div><object type="application/x-shockwave-flash" data="/resources/Files/Auglysingar/ISL_65676_160x330.swf" width="160" height="330"><param name="movie" value="/resources/Files/Auglysingar/ISL_65676_160x330.swf"/><a href="/English/ShopsRestaurants/"><img src="/resources/Files/Auglysingar/ISL_65676_160x330.gif" width="160" height="330" alt="" border="0"/></a></object> <a href="/framework/resources/forms/ads.aspx?ID=121" target="_self"><img src="/resources/Images/Template-Ads/fle-68511-google-ads-160x338-en.jpg" border="0" alt="sumar 2014 - verslanir -en"/></a></div>--><div><iframe height="338" src="http://apache.hvitahusid.is/isavia/wheninkef/kefairport/160x338_ensk/160x338_kef_besturBetri_en_2.html" frameborder="0" width="160" scrolling="no"></iframe></div></div><div class="clear"></div><ul class="ads"> <li><a href="/English/Before-Departure/Self-service-check-in/"><img border="0" alt="" src="/resources/images/template/2010/ad-2-en.gif"/></a></li><li><a href="/English/Transportation/Parking/"><img border="0" alt="" src="/resources/images/template/2010/ad-3-en.gif"/></a></li><li><a target="_new" href="/resources/map-en-2009/vefkort_eng.html"><img border="0" alt="" src="/resources/images/template/2010/ad-4-en.gif"/></a></li><li><a href="http://b2b.kefairport.is/english/"><img border="0" alt="" src="/resources/images/template/2010/ad-5.gif"/></a></li><li><a href="/English/For-the-passenger/Lost-Found/"><img border="0" alt="" src="/resources/images/template/2010/ad-6-en.gif"/></a></li></ul><ul class="media"> <li><a class="facebook" target="_blank" href="http://www.facebook.com/kefairport">Facebook</a></li><li><a class="youtube" target="_blank" href="http://www.youtube.com/kefairport">Youtube</a></li><li><a class="twitter" target="_blank" href="http://twitter.com/kefairport">Twitter</a></li><li><a class="myspace" target="_blank" href="http://flickr.com/kefairport">Flickr</a></li></ul><div class="clear"></div><div></div></div><div id="right"><div class="row"><div class="left left-content-right"><h2 class="title">Arrivals</h2><div class="clear"></div><div class="table-area"><div class="tables"><div style="width:751px;background: url(/resources/images/template/2010/b2b/bg-content-list.gif) repeat-x bottom left rgb(244,244,244);padding:15px 7px;"><strong>Day:</strong> <select onchange="location.href=this.value;"><option value="/English/Timetables/Arrivals/Yesterday/">28. December</option><option selected="selected" value="/English/Timetables/Arrivals/">29. December</option><option value="/English/Timetables/Arrivals/Tomorrow/">30. December</option></select></div><table style="width:765px;background:#f6f6f6;"> <tbody> <tr> <th width="10%" align="left">Date</th> <th width="10%" align="left">Flight Nr.</th> <th width="20%" align="left">Airline</th> <th width="20%" align="left">From</th> <th width="10%" align="left">Schedule. Time</th> <th width="20%" align="left">Status</th> </tr><tr> <td>29. Dec</td><td>WW126</td><td>WOW air</td><td>Boston Logan Intl</td><td>04:05</td><td>Landed 05:06</td></tr><tr> <td>29. Dec</td><td>WW118</td><td>WOW air</td><td>Baltimore Washington Intl</td><td>05:10</td><td>Landed 05:45</td></tr><tr> <td>29. Dec</td><td>FI670</td><td>Icelandair</td><td>Denver Intl</td><td>06:35</td><td>Landed 06:27</td></tr><tr> <td>29. Dec</td><td>FI622</td><td>Icelandair</td><td>New York Newark Liberty Intl</td><td>06:35</td><td>Landed 06:40</td></tr><tr> <td>29. Dec</td><td>FI630</td><td>Icelandair</td><td>Boston Logan Intl</td><td>06:40</td><td>Landed 06:42</td></tr><tr> <td>29. Dec</td><td>FI602</td><td>Icelandair</td><td>Toronto Lester B Pearson</td><td>06:25</td><td>Landed 06:44</td></tr><tr> <td>29. Dec</td><td>FI614</td><td>Icelandair</td><td>New York JFK</td><td>06:45</td><td>Landed 06:48</td></tr><tr> <td>29. Dec</td><td>FI680</td><td>Icelandair</td><td>Seattle Tacoma Intl</td><td>06:45</td><td>Landed 06:58</td></tr><tr> <td>29. Dec</td><td>FI656</td><td>Icelandair</td><td>Minneapolis St Paul Intl</td><td>06:30</td><td>Landed 07:09</td></tr><tr> <td>29. Dec</td><td>FI741</td><td>Icelandair (cargo)</td><td>Liege</td><td>07:40</td><td>Landed 07:30</td></tr><tr> <td>29. Dec</td><td>BBD6810</td><td>Bluebird ehf. (cargo)</td><td>Dublin</td><td>08:20</td><td>Landed 08:28</td></tr><tr> <td>29. Dec</td><td>EZY1805</td><td>easyJet</td><td>Manchester</td><td>10:35</td><td>Landed 10:12</td></tr><tr> <td>29. Dec</td><td>EZY2295</td><td>easyJet</td><td>London Luton</td><td>10:50</td><td>Landed 10:33</td></tr><tr> <td>29. Dec</td><td>EZY6001</td><td>easyJet</td><td>Bristol Lulsgate</td><td>10:50</td><td>Landed 10:42</td></tr><tr> <td>29. Dec</td><td>SK4787</td><td>SAS</td><td>Oslo Airport</td><td>12:00</td><td>Landed 11:47</td></tr><tr> <td>29. Dec</td><td>DY1170</td><td>Norwegian Air</td><td>Oslo Airport</td><td>12:20</td><td>Landed 12:31</td></tr><tr> <td>29. Dec</td><td>FI2351</td><td>Icelandair</td><td>Egilsstadir</td><td>12:30</td><td>Landed 13:08</td></tr><tr> <td>29. Dec</td><td>WW811</td><td>WOW air</td><td>London Gatwick</td><td>14:25</td><td>Landed 14:18</td></tr><tr> <td>29. Dec</td><td>WW903</td><td>WOW air</td><td>Copenhagen</td><td>14:25</td><td>Landed 14:28</td></tr><tr> <td>29. Dec</td><td>WW721</td><td>WOW air</td><td>Berlin Schoenefeld</td><td>14:25</td><td>Landed 14:44</td></tr><tr> <td>29. Dec</td><td>FI555</td><td>Icelandair</td><td>Brussels Natl</td><td>15:15</td><td>Landed 15:17</td></tr><tr> <td>29. Dec</td><td>FI501</td><td>Icelandair</td><td>Amsterdam Schiphol</td><td>15:30</td><td>Landed 15:28</td></tr><tr> <td>29. Dec</td><td>FI431</td><td>Icelandair</td><td>Glasgow</td><td>15:40</td><td>Landed 15:30</td></tr><tr> <td>29. Dec</td><td>FI205</td><td>Icelandair</td><td>Copenhagen</td><td>15:30</td><td>Landed 15:35</td></tr><tr> <td>29. Dec</td><td>FI543</td><td>Icelandair</td><td>Paris Charles De Gaulle</td><td>15:50</td><td>Landed 15:44</td></tr><tr> <td>29. Dec</td><td>FI471</td><td>Icelandair</td><td>London Gatwick</td><td>15:30</td><td>Landed 15:47</td></tr><tr> <td>29. Dec</td><td>FI451</td><td>Icelandair</td><td>London Heathrow</td><td>16:00</td><td>Landed 16:00</td></tr><tr> <td>29. Dec</td><td>FI521</td><td>Icelandair</td><td>Frankfurt Main</td><td>16:10</td><td>Landed 16:27</td></tr><tr> <td>29. Dec</td><td>FI319</td><td>Icelandair</td><td>Oslo Airport</td><td>15:45</td><td>Landed 16:20</td></tr><tr> <td>29. Dec</td><td>FI307</td><td>Icelandair</td><td>Stockholm Arlanda</td><td>15:45</td><td>Landed 16:26</td></tr><tr> <td>29. Dec</td><td>FI533</td><td>Icelandair</td><td>Munich </td><td>16:00</td><td>Landed 16:29</td></tr><tr> <td>29. Dec</td><td>EZY2297</td><td>easyJet</td><td>London Luton</td><td>17:30</td><td>Landed 17:29</td></tr><tr> <td>29. Dec</td><td>EZY6941</td><td>easyJet</td><td>Edinburgh</td><td>18:55</td><td>Confirm. 18:34</td></tr><tr> <td>29. Dec</td><td>FI213</td><td>Icelandair</td><td>Copenhagen</td><td>22:20</td><td></td></tr><tr> <td>29. Dec</td><td>WW815</td><td>WOW air</td><td>London Gatwick</td><td>22:50</td><td></td></tr><tr> <td>29. Dec</td><td>FI455</td><td>Icelandair</td><td>London Heathrow</td><td>23:35</td><td></td></tr></tbody></table></div></div></div></div></div></div><div id="footer"><a class="orange" href="/English/">Home</a><br/>Keflavik International Airport | 235 Keflavikurflugvollur, Iceland | <a href="mailto:kefairport@kefairport.is">kefairport@kefairport.is</a> | Phone: +354 425 6000 | Fax: +354 425 6010</div></div></div></div></div></div><div id="ad-container"><a target="_new" href="http://www.inspiredbyiceland.com"><img title="Inspired by Iceland" border="0" alt="Inspired by Iceland" src="/resources/Images/inspired_kef.gif"/></a></div><script language="javascript" type="text/javascript"><!-- var p_run_js=0;//--></script><script language="javascript1.1" type="text/javascript"><!-- var p_run_js=1;//--></script><script language="javascript" type="text/javascript"><!--//<![CDATA[ var service_id="1813";var portion="1"; var page="Keflavik+Airport+Arrivals.+Scheduled+%26+ETA+-+Keflavik+International+Airport"; if(!p_run_js){document.write('<img width="1" height="1" src="http://kefairport-is.teljari.is/potency/potency.php?o='+service_id+';i='+portion+';p='+page+';j=1.0" alt="" border="0"/>');}//]]>//--></script><script language="javascript1.1" type="text/javascript" src="http://kefairport-is.teljari.is/potency/js/potency.js"></script><noscript><img width="1" height="1" src="http://kefairport-is.teljari.is/potency/potency.php?o=1813;i=1;p=Keflavik+Airport+Arrivals.+Scheduled+%26+ETA+-+Keflavik+International+Airport" alt="" border="0"/></noscript><script type="text/javascript">var gaJsHost=(("https:"==document.location.protocol) ? "https://ssl." : "http://www.");document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));</script><script type="text/javascript">try{var pageTracker=_gat._getTracker("UA-7039522-2");pageTracker._trackPageview();}catch(err){}</script><noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PCHVQB"height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-PCHVQB');</script><script type="text/javascript" src="http://d.yimg.com/mi/eu/ywa.js"></script><script type="text/javascript">/*globals YWA*/var YWATracker=YWA.getTracker("10002046350912");//YWATracker.setDocumentName("");//YWATracker.setDocumentGroup("");YWATracker.submit();</script><noscript><div><img src="http://s.analytics.yahoo.com/p.pl?a=10002046350912&amp;js=no" width="1" height="1" alt=""/></div></noscript></body></html>`;
    const flights = extractFlights(data, 2015);
    const exptectedFlights = [
      { date: '29. Dec',
        flightNum: 'WW126',
        airline: 'WOW air',
        location: 'Boston Logan Intl',
        scheduled: '04:05',
        status: 'Landed 05:06',
        id: '1451361900000WW126',
        timestamp: 1451361900000,
      },
      { date: '29. Dec',
        flightNum: 'WW118',
        airline: 'WOW air',
        location: 'Baltimore Washington Intl',
        scheduled: '05:10',
        status: 'Landed 05:45',
        id: '1451365800000WW118',
        timestamp: 1451365800000,
      },
      { date: '29. Dec',
        flightNum: 'FI670',
        airline: 'Icelandair',
        location: 'Denver Intl',
        scheduled: '06:35',
        status: 'Landed 06:27',
        id: '1451370900000FI670',
        timestamp: 1451370900000,
      },
      { date: '29. Dec',
        flightNum: 'FI622',
        airline: 'Icelandair',
        location: 'New York Newark Liberty Intl',
        scheduled: '06:35',
        status: 'Landed 06:40',
        id: '1451370900000FI622',
        timestamp: 1451370900000,
      },
      { date: '29. Dec',
        flightNum: 'FI630',
        airline: 'Icelandair',
        location: 'Boston Logan Intl',
        scheduled: '06:40',
        status: 'Landed 06:42',
        id: '1451371200000FI630',
        timestamp: 1451371200000,
      },
      { date: '29. Dec',
        flightNum: 'FI602',
        airline: 'Icelandair',
        location: 'Toronto Lester B Pearson',
        scheduled: '06:25',
        status: 'Landed 06:44',
        id: '1451370300000FI602',
        timestamp: 1451370300000,
      },
      { date: '29. Dec',
        flightNum: 'FI614',
        airline: 'Icelandair',
        location: 'New York JFK',
        scheduled: '06:45',
        status: 'Landed 06:48',
        id: '1451371500000FI614',
        timestamp: 1451371500000,
      },
      { date: '29. Dec',
        flightNum: 'FI680',
        airline: 'Icelandair',
        location: 'Seattle Tacoma Intl',
        scheduled: '06:45',
        status: 'Landed 06:58',
        id: '1451371500000FI680',
        timestamp: 1451371500000,
      },
      { date: '29. Dec',
        flightNum: 'FI656',
        airline: 'Icelandair',
        location: 'Minneapolis St Paul Intl',
        scheduled: '06:30',
        status: 'Landed 07:09',
        id: '1451370600000FI656',
        timestamp: 1451370600000,
      },
      { date: '29. Dec',
        flightNum: 'FI741',
        airline: 'Icelandair (cargo)',
        location: 'Liege',
        scheduled: '07:40',
        status: 'Landed 07:30',
        id: '1451374800000FI741',
        timestamp: 1451374800000,
      },
      { date: '29. Dec',
        flightNum: 'BBD6810',
        airline: 'Bluebird ehf. (cargo)',
        location: 'Dublin',
        scheduled: '08:20',
        status: 'Landed 08:28',
        id: '1451377200000BBD6810',
        timestamp: 1451377200000,
      },
      { date: '29. Dec',
        flightNum: 'EZY1805',
        airline: 'easyJet',
        location: 'Manchester',
        scheduled: '10:35',
        status: 'Landed 10:12',
        id: '1451385300000EZY1805',
        timestamp: 1451385300000,
      },
      { date: '29. Dec',
        flightNum: 'EZY2295',
        airline: 'easyJet',
        location: 'London Luton',
        scheduled: '10:50',
        status: 'Landed 10:33',
        id: '1451386200000EZY2295',
        timestamp: 1451386200000,
      },
      { date: '29. Dec',
        flightNum: 'EZY6001',
        airline: 'easyJet',
        location: 'Bristol Lulsgate',
        scheduled: '10:50',
        status: 'Landed 10:42',
        id: '1451386200000EZY6001',
        timestamp: 1451386200000,
      },
      { date: '29. Dec',
        flightNum: 'SK4787',
        airline: 'SAS',
        location: 'Oslo Airport',
        scheduled: '12:00',
        status: 'Landed 11:47',
        id: '1451390400000SK4787',
        timestamp: 1451390400000,
      },
      { date: '29. Dec',
        flightNum: 'DY1170',
        airline: 'Norwegian Air',
        location: 'Oslo Airport',
        scheduled: '12:20',
        status: 'Landed 12:31',
        id: '1451391600000DY1170',
        timestamp: 1451391600000,
      },
      { date: '29. Dec',
        flightNum: 'FI2351',
        airline: 'Icelandair',
        location: 'Egilsstadir',
        scheduled: '12:30',
        status: 'Landed 13:08',
        id: '1451392200000FI2351',
        timestamp: 1451392200000,
      },
      { date: '29. Dec',
        flightNum: 'WW811',
        airline: 'WOW air',
        location: 'London Gatwick',
        scheduled: '14:25',
        status: 'Landed 14:18',
        id: '1451399100000WW811',
        timestamp: 1451399100000,
      },
      { date: '29. Dec',
        flightNum: 'WW903',
        airline: 'WOW air',
        location: 'Copenhagen',
        scheduled: '14:25',
        status: 'Landed 14:28',
        id: '1451399100000WW903',
        timestamp: 1451399100000,
      },
      { date: '29. Dec',
        flightNum: 'WW721',
        airline: 'WOW air',
        location: 'Berlin Schoenefeld',
        scheduled: '14:25',
        status: 'Landed 14:44',
        id: '1451399100000WW721',
        timestamp: 1451399100000,
      },
      { date: '29. Dec',
        flightNum: 'FI555',
        airline: 'Icelandair',
        location: 'Brussels Natl',
        scheduled: '15:15',
        status: 'Landed 15:17',
        id: '1451402100000FI555',
        timestamp: 1451402100000,
      },
      { date: '29. Dec',
        flightNum: 'FI501',
        airline: 'Icelandair',
        location: 'Amsterdam Schiphol',
        scheduled: '15:30',
        status: 'Landed 15:28',
        id: '1451403000000FI501',
        timestamp: 1451403000000,
      },
      { date: '29. Dec',
        flightNum: 'FI431',
        airline: 'Icelandair',
        location: 'Glasgow',
        scheduled: '15:40',
        status: 'Landed 15:30',
        id: '1451403600000FI431',
        timestamp: 1451403600000,
      },
      { date: '29. Dec',
        flightNum: 'FI205',
        airline: 'Icelandair',
        location: 'Copenhagen',
        scheduled: '15:30',
        status: 'Landed 15:35',
        id: '1451403000000FI205',
        timestamp: 1451403000000,
      },
      { date: '29. Dec',
        flightNum: 'FI543',
        airline: 'Icelandair',
        location: 'Paris Charles De Gaulle',
        scheduled: '15:50',
        status: 'Landed 15:44',
        id: '1451404200000FI543',
        timestamp: 1451404200000,
      },
      { date: '29. Dec',
        flightNum: 'FI471',
        airline: 'Icelandair',
        location: 'London Gatwick',
        scheduled: '15:30',
        status: 'Landed 15:47',
        id: '1451403000000FI471',
        timestamp: 1451403000000,
      },
      { date: '29. Dec',
        flightNum: 'FI451',
        airline: 'Icelandair',
        location: 'London Heathrow',
        scheduled: '16:00',
        status: 'Landed 16:00',
        id: '1451404800000FI451',
        timestamp: 1451404800000,
      },
      { date: '29. Dec',
        flightNum: 'FI521',
        airline: 'Icelandair',
        location: 'Frankfurt Main',
        scheduled: '16:10',
        status: 'Landed 16:27',
        id: '1451405400000FI521',
        timestamp: 1451405400000,
      },
      { date: '29. Dec',
        flightNum: 'FI319',
        airline: 'Icelandair',
        location: 'Oslo Airport',
        scheduled: '15:45',
        status: 'Landed 16:20',
        id: '1451403900000FI319',
        timestamp: 1451403900000,
      },
      { date: '29. Dec',
        flightNum: 'FI307',
        airline: 'Icelandair',
        location: 'Stockholm Arlanda',
        scheduled: '15:45',
        status: 'Landed 16:26',
        id: '1451403900000FI307',
        timestamp: 1451403900000,
      },
      { date: '29. Dec',
        flightNum: 'FI533',
        airline: 'Icelandair',
        location: 'Munich ',
        scheduled: '16:00',
        status: 'Landed 16:29',
        id: '1451404800000FI533',
        timestamp: 1451404800000,
      },
      { date: '29. Dec',
        flightNum: 'EZY2297',
        airline: 'easyJet',
        location: 'London Luton',
        scheduled: '17:30',
        status: 'Landed 17:29',
        id: '1451410200000EZY2297',
        timestamp: 1451410200000,
      },
      { date: '29. Dec',
        flightNum: 'EZY6941',
        airline: 'easyJet',
        location: 'Edinburgh',
        scheduled: '18:55',
        status: 'Confirm. 18:34',
        id: '1451415300000EZY6941',
        timestamp: 1451415300000,
      },
      { date: '29. Dec',
        flightNum: 'FI213',
        airline: 'Icelandair',
        location: 'Copenhagen',
        scheduled: '22:20',
        status: '',
        id: '1451427600000FI213',
        timestamp: 1451427600000,
      },
      { date: '29. Dec',
        flightNum: 'WW815',
        airline: 'WOW air',
        location: 'London Gatwick',
        scheduled: '22:50',
        status: '',
        id: '1451429400000WW815',
        timestamp: 1451429400000,
      },
      { date: '29. Dec',
        flightNum: 'FI455',
        airline: 'Icelandair',
        location: 'London Heathrow',
        scheduled: '23:35',
        status: '',
        id: '1451432100000FI455',
        timestamp: 1451432100000,
      },
    ];
    expect(flights).toEqual(exptectedFlights);
  });
});
